// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUTgjL5ABOWTEb9Hdz_pIq5vKrRK7q1I',
    appId: '1:891791207662:android:e165b9583ea51b047a97ff',
    messagingSenderId: '891791207662',
    projectId: 'flutter-prep-1eddb',
    databaseURL: 'https://flutter-prep-1eddb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-1eddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIA6Emubu18wbhHemRhxPmwXANf_1aFFI',
    appId: '1:891791207662:ios:f6f7ef56c83d8e837a97ff',
    messagingSenderId: '891791207662',
    projectId: 'flutter-prep-1eddb',
    databaseURL: 'https://flutter-prep-1eddb-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-1eddb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
